# Generated by Django 4.2.6 on 2023-11-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Firstname',
            field=models.CharField(max_length=50),
        ),
    ]
